### ISSUE TITLE
Do not break everything once Meilisearch is not reachable

### ISSUE THREAD

**Issue by malteriechmann** [visuellverstehen/t3meilisearch#4] opened 2022-02-16 10:18 UTC
Instead of break the frontend and display an error message, it would be nice, if we could log an error message when Meilisearch is not reachable.

**Comment by runepiper** [comment] 2022-02-16 10:25
There shouldn't be an error message anymore.

**Comment by malteriechmann** [comment] 2022-02-16 10:30
I still get the same problem.

Configuration:
```
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['t3meilisearch']['host'] = 'wrong-host.com:7700';
```

Error:
```
cURL error 6: Could not resolve host: wrong-host.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://wrong-host.com:7700/indexes/pages/documents
```

<img width="1190" alt="Screenshot 2022-02-16 at 11 28 54" src="https://user-images.githubusercontent.com/656568/154246028-332259c3-8c4d-454b-bd6c-74c8017a7028.png">

**Comment by runepiper** [comment] 2022-02-16 10:37
Sorry, couldn't reproduce at first, but with your example I could. Now it should be fixed.

**Comment by malteriechmann** [comment] 2022-02-16 10:52
The page is not breaking anymore. Nice :)

But I think we should still log the error of debug purposes.

**Comment by runepiper** [comment] 2022-02-16 11:57
Added logging.

**Closed as completed** 2022-02-16 12:05 UTC
Labels: enhancement
